### ISSUE TITLE
Observation on Banking-System : It Cannot Register New User from Registration Interface/Page

### ISSUE THREAD

**Issue by eteimopius** [banksystembg/BankSystem#234]
I would like to thank the Author of the Banking System for the wonderful and highly educative work done on the project.

However, I observed that one is unable to register a new user into the database "AspNetUser Table' using the Register.html interface/page. The system successfully login with the initial seeded data but one cannot register a new user into the database.

Thus, Recaptcha Secret keys were added to the AppSettings Json file, and ConfirmEmail was also disabled on  StartUp.cs file but it could not resolve the inability to register a new user.

It would be appreciated if you could give further steps one could explore in resolving the problem.

Thanks immensely

**Comment by melikpehlivanov** [comment]
Hey! Apologies for the delayed response. This project isn't currently in active development so that's one of the reasons for the delayed response. Could you give me more details about the issue you're encountering? It would be helpful to have some error descriptions along with screenshots or any other relevant information so I can better understand what's going on.

**Comment by eteimopius** [comment]
Thank you sir for your response, I have been able to figure out the problem
and resolved it. Thanks so much for your excellent Project.  I have learnt
a lot, reading through the Project's code line by line.

I look forward to learning from your wealth of knowledge, going forward.

Best Regards

**Comment by melikpehlivanov** [comment]
Hey, that's fantastic news! I'm really pleased to hear that you've managed to resolve the issue on your own. In that case, I'll go ahead and mark this issue as resolved. 😊 Have a wonderful day!
